version: '3.8'

services:
  wifi-scanner:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-production-secret-key-here
      - DATABASE_URI=sqlite:////tmp/wifi_scanner.db
      - UPLOAD_FOLDER=uploads
      - MAX_CONTENT_LENGTH=1048576
    # Volumes disabled temporarily to get app working
    # volumes:
    #   - wifi_data:/app/data
    #   - wifi_uploads:/app/uploads
    restart: unless-stopped

volumes:
  wifi_data:
  wifi_uploads: